//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.12 at 02:50:56 PM IST 
//


package ie.decoder.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="XbyY">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://www.decoder.ie/namespaces}gridAttributes"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cell" maxOccurs="81" minOccurs="81">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Value" type="{http://www.decoder.ie/namespaces}ZeroToNine"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{http://www.decoder.ie/namespaces}cellAttributes"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "xbyY",
    "cell"
})
@XmlRootElement(name = "grid")
public class Grid {

    @XmlElement(name = "XbyY", required = true)
    protected Grid.XbyY xbyY;
    @XmlElement(required = true)
    protected List<Grid.Cell> cell;

    /**
     * Gets the value of the xbyY property.
     * 
     * @return
     *     possible object is
     *     {@link Grid.XbyY }
     *     
     */
    public Grid.XbyY getXbyY() {
        return xbyY;
    }

    /**
     * Sets the value of the xbyY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Grid.XbyY }
     *     
     */
    public void setXbyY(Grid.XbyY value) {
        this.xbyY = value;
    }

    /**
     * Gets the value of the cell property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cell property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCell().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Grid.Cell }
     * 
     * 
     */
    public List<Grid.Cell> getCell() {
        if (cell == null) {
            cell = new ArrayList<Grid.Cell>();
        }
        return this.cell;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Value" type="{http://www.decoder.ie/namespaces}ZeroToNine"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://www.decoder.ie/namespaces}cellAttributes"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Cell {

        @XmlElement(name = "Value", defaultValue = "0")
        protected int value;
        @XmlAttribute(name = "X", namespace = "http://www.decoder.ie/namespaces", required = true)
        protected int x;
        @XmlAttribute(name = "Y", namespace = "http://www.decoder.ie/namespaces", required = true)
        protected int y;
        @XmlAttribute(namespace = "http://www.decoder.ie/namespaces", required = true)
        protected int index;

        /**
         * Gets the value of the value property.
         * 
         */
        public int getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(int value) {
            this.value = value;
        }

        /**
         * Gets the value of the x property.
         * 
         */
        public int getX() {
            return x;
        }

        /**
         * Sets the value of the x property.
         * 
         */
        public void setX(int value) {
            this.x = value;
        }

        /**
         * Gets the value of the y property.
         * 
         */
        public int getY() {
            return y;
        }

        /**
         * Sets the value of the y property.
         * 
         */
        public void setY(int value) {
            this.y = value;
        }

        /**
         * Gets the value of the index property.
         * 
         */
        public int getIndex() {
            return index;
        }

        /**
         * Sets the value of the index property.
         * 
         */
        public void setIndex(int value) {
            this.index = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://www.decoder.ie/namespaces}gridAttributes"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class XbyY {

        @XmlAttribute(namespace = "http://www.decoder.ie/namespaces", required = true)
        protected int width;
        @XmlAttribute(namespace = "http://www.decoder.ie/namespaces", required = true)
        protected int length;

        /**
         * Gets the value of the width property.
         * 
         */
        public int getWidth() {
            return width;
        }

        /**
         * Sets the value of the width property.
         * 
         */
        public void setWidth(int value) {
            this.width = value;
        }

        /**
         * Gets the value of the length property.
         * 
         */
        public int getLength() {
            return length;
        }

        /**
         * Sets the value of the length property.
         * 
         */
        public void setLength(int value) {
            this.length = value;
        }

    }

}
