//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.12 at 02:50:56 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.decoder.ie/namespaces", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ie.decoder.xsd;
